SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@localhost:5433/License'
EMAIL = 'coach.code@yahoo.com'
# PASSWORD = 'phydxnlwrgnsnivx'
PASSWORD = 'sgviozxuruxffieb'
SECRET_KEY = 'fgeFWu+YDBd9Xc$cjAk8k2UpvDgA4*'
OPEN_AI_API_KEY = 'sk-proj-yefZbFAevfiOJGU3jdy7T3BlbkFJhW97QpcMpF0EVvRsQZVU'
ASSISTANT_ID = 'asst_i87AGUqWxiEBuHwxTkI43R1A'